/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_live555_myRtspClientJni */

#ifndef _COM_THUNDERCOMM_RTSP_TSRTSPNATIVE_H_
#define _COM_THUNDERCOMM_RTSP_TSRTSPNATIVE_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fly_live555_myRtspClientJni
 * Method:    rtspClientOpenJni
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_thundercomm_rtsp_TsRtspNative_rtspClientOpenJni
        (JNIEnv *, jobject, jstring, jint);


/*
 * Class:     com_example_fly_live555_myRtspClientJni
 * Method:    rtspClientCloseJni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_thundercomm_rtsp_TsRtspNative_rtspClientCloseJni
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif  // _COM_THUNDERCOMM_RTSP_TSRTSPNATIVE_H_
