/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thundercomm_eBox_Utils_BitmapUtils */

#ifndef _Included_com_thundercomm_eBox_Utils_BitmapUtils
#define _Included_com_thundercomm_eBox_Utils_BitmapUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thundercomm_eBox_Utils_BitmapUtils
 * Method:    rotateBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_thundercomm_eBox_Utils_BitmapUtils_rotateBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_thundercomm_eBox_Utils_BitmapUtils
 * Method:    convertBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_thundercomm_eBox_Utils_BitmapUtils_convertBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_thundercomm_eBox_Utils_BitmapUtils
 * Method:    mirrorBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_thundercomm_eBox_Utils_BitmapUtils_mirrorBitmap
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
